### ISSUE TITLE
Crash to desktop on 1.19.2 - possible mod conflict

### ISSUE THREAD

**Issue by Gamemassa** [TerraformersMC/Terrestria#277] opened 2022-09-12 17:09 UTC
Minecraft version: 1.19.2
Fabric version: 0.14.9 (latest)
Terrestria version: 5.0.0

My game is crashing to desktop when I try to create a new singleplayer world with the latest versions of Terrestria and Oh the Biomes You'll Go (crash report attached). I'm not really sure what's causing it, or if it is a mod conflict, but when I run separately with each of the mods, I can create new worlds without issues.

https://gist.github.com/Gamemassa/3d3852f59c64874cc6bc2b72c132c72c

**Comment by gniftygnome** [comment] 2022-09-12 17:13
Duplicate of #275.  Thanks for the full logs though, that can be useful.

**Closed as not planned by gniftygnome** 2022-09-12 17:13 UTC
