### ISSUE TITLE
Rare incompatibility with Lithium.

### ISSUE THREAD

**Issue by K0-RR** [TerraformersMC/Terrestria#233] opened 2021-01-31 02:15 UTC
Please see https://github.com/jellysquid3/lithium-fabric/issues/207

**Comment by coderbot16** [comment] 2021-01-31 02:57
This appears to be a duplicate of https://github.com/TerraformersMC/Terrestria/issues/232, so I will close this issue in favor of the other one. If my assessment is incorrect, please tell me and I will reopen the issue.

**Closed as completed** 2021-01-31 02:58 UTC
