### ISSUE TITLE
[Crash][Quilt][1.19.2] Crash on start up

### ISSUE THREAD

**Issue by EightBlade** [TerraformersMC/Terrestria#287] opened 2022-11-28 04:36 UTC
I've had multiple crashes on start up with Terrestria installed. I have no idea what's causing it, and have thus included a log to hopefully help diagnose it.

https://pastebin.com/xdJdBLJu

**Comment by gniftygnome** [comment] 2022-11-28 16:09
Duplicate of #278.

**Closed as not planned** 2022-11-28 16:09 UTC
