### ISSUE TITLE
Feature order cycle crash with Biomes You'll Go and William Wythers Overhauled Overworld

### ISSUE THREAD

**Issue by kuddyh3ct0r** [TerraformersMC/Terrestria#275] opened 2022-09-03 23:13 UTC
Minecraft crashed while trying to load a world with terrestria + oh the biomes youll go.
The same thing happened with wythers overhauled overworld
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2022-09-03 16:07:03
Description: Exception generating new chunk

java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / byg:firecracker_shrubland]=net.minecraft.class_1959@6ab3a35f}, Reference{ResourceKey[minecraft:worldgen/biome / terrestria:outback]=net.minecraft.class_1959@1947a514}]
	at net.minecraft.class_7510.method_44210(class_7510.java:100)
	at net.minecraft.class_2794.mdd895a3$lambda$updateFeaturesPerStep$1$0(class_2794.java:1354)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_2794.method_12102(class_2794.java:397)
	at net.minecraft.class_2806.method_20613(class_2806.java:145)
	at net.minecraft.class_2806.method_12154(class_2806.java:292)
	at net.minecraft.class_3898.method_17225(class_3898.java:773)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:771)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_7510.method_44210(class_7510.java:100)
	at net.minecraft.class_2794.mdd895a3$lambda$updateFeaturesPerStep$1$0(class_2794.java:1354)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at net.minecraft.class_2794.method_12102(class_2794.java:397)
	at net.minecraft.class_2806.method_20613(class_2806.java:145)
	at net.minecraft.class_2806.method_12154(class_2806.java:292)
	at net.minecraft.class_3898.method_17225(class_3898.java:773)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:771)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)

-- Chunk to be generated --
Details:
	Location: 0,0
	Position hash: 0
	Generator: net.minecraft.class_3754@33110df8
Stacktrace:
	at net.minecraft.class_3898.method_17225(class_3898.java:773)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:771)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 7921
	Level dimension: minecraft:overworld
	Level spawn location: World: (24,64,24), Section: (at 8,0,8 in 1,4,1; chunk contains blocks 16,-64,16 to 31,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:367)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:315)
	at net.minecraft.class_1132.method_3823(class_1132.java:82)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1259301688 bytes (1200 MiB) / 4529848320 bytes (4320 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Virtual Desktop Monitor
	Graphics card #0 vendor: Virtual Desktop, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=15.39.56.845
	Graphics card #1 name: NVIDIA GeForce RTX 2070
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f07
	Graphics card #1 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 33722.16
	Virtual memory used (MB): 13019.21
	Swap memory total (MB): 17408.00
	Swap memory used (MB): 319.03
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		byg: Oh The Biomes You'll Go 2.0.0.10
		fabric-api: Fabric API 0.60.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.9+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.17+aeb40ebe90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.20+aeb40ebe90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.1+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.11+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.7+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.28+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.34+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.3+aeb40ebe90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.1+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.5+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.8+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.30+aeb40ebe90
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.18+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.28+aeb40ebe90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.28+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.21+aeb40ebe90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.7+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.28+aeb40ebe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.18+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.2+aeb40ebe90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.3+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.6+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.3+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.14+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.17+aeb40ebe90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.4+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.21+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.11+aeb40ebe90
			fabric-particles-v1: Fabric Particles (v1) 1.0.10+aeb40ebe90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.24+aeb40ebe90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.10+aeb40ebe90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.12+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.20+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.22+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.16+aeb40ebe90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.11+e62f51a390
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.1+aeb40ebe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.26+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.13+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.20+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.11+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.0+42d99c3290
		fabricloader: Fabric Loader 0.14.9
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.2
		optifabric: OptiFabric 1.13.16
			mm: Manningham Mills 2.3
		terrablender: TerraBlender 2.0.1.125
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		terrestria: Terrestria 5.0.0
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 4.1.1
			terraform-config-api-v1: Terraform Config API (v1) 4.1.1
			terraform-dirt-api-v1: Terraform Dirt API (v1) 4.1.1
			terraform-shapes-api-v1: Terraform Shapes API (v1) 4.1.1
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 4.1.1
			terraform-tree-api-v1: Terraform Tree API (v1) 4.1.1
			terraform-wood-api-v1: Terraform Wood API (v1) 4.1.1
			terrestria-client: Terrestria: Client 5.0.0
			terrestria-common: Terrestria: Common 5.0.0
			terrestria-worldgen: Terrestria: World Generation 5.0.0
		traverse: Traverse 6.0.0
			traverse-client: Traverse: Client 6.0.0
			traverse-common: Traverse: Common 6.0.0
			traverse-worldgen: Traverse: World Generation 6.0.0
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.9-1.19.2
	OptiFine Version: OptiFine_1.19.2_HD_U_H9
	OptiFine Build: 20220820-230904
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 516.94
	OpenGlRenderer: NVIDIA GeForce RTX 2070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.19.2
	OptiFine jar version: OptiFine_1.19.2_HD_U_H9
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/braya/AppData/Roaming/.minecraft/.optifine/OptiFine_1.19.2_HD_U_H9/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by gniftygnome** [comment] 2022-09-03 23:40
I'll take a look at this, but not right away; our feature order is compatible with Vanilla but as the last player to the table, trying to match it to all the other biome mods could be a practically unbounded amount of work.

**Comment by dandin87** [comment] 2022-09-06 20:24
All of Fabric 5 dev here. Did some testing. Biome Mods - BYG/BiomeMakeover/graveyard_biomes/promenade/wildbackport/terralith/terrestria/traverse/cinderscapes
After disabling Terrestria/Outback all the other biomes seem to work fine. Didn't get to test Oasis as it couldn't find it close enough. But I did locate and teleport to all the other Terrestria biomes.
316 Biomes - https://gist.github.com/dandin87/cc61bf6c6c7c69b32f7702d562fe66fd

**Comment by gniftygnome** [comment] 2022-09-06 20:57
I thought we were past the inclusion deadline for AoF.  If the implication is you are still looking at our mods for inclusion in 1.19 then I would be willing to bump up the priority on this.

Regarding the difficulty of resolving feature order cycles, I would like to point out it's not as simple as folks seem to think.  Any adjustment I make to one biome may impact others and/or create new, different feature order cycles with other mods.  Combinations of other mods can have near-cycles which only succeed because no biome uses a particular combination of features.  It's therefore possible for a feature order cycle between Terrestria and other mods to be impossible to resolve purely within Terrestria (aside from removing one or more features from the biome).  This stuff can take a lot of time to fix (and the quick glance I gave it before my first response indicated it wasn't clear-cut what features were involved, so this one isn't a quick fix at any rate).

**Comment by dandin87** [comment] 2022-09-06 22:00
I was just indicating that the Outback biome can be disabled in the config for anyone having the issue. A simple workaround. 
And letting you know it seemed to work quite nicely with pretty much all biome mods after disabling the Outback.
I am pushing for the inclusion of all the Terraformers mods again though, like we had in aof3.

**Comment by gniftygnome** [comment] 2022-09-06 22:05
> I am pushing for the inclusion of all the Terraformers mods again though, like we had in aof3.
:+1: 

I do expect to work on this before too long ... there's a Vistas issue with Iris next up, and also the question of whether to devote time to backporting Terrestria and Cinderscapes to 1.19(.0) in contention for next in line.

**Comment by gniftygnome** [comment] 2022-09-12 17:48
This is Vanilla (from the Savanna biome definition via Yarn for 1.19.2):
```java
        OverworldBiomeCreator.addBasicFeatures(lv);
        if (!windswept) {
            DefaultBiomeFeatures.addSavannaTallGrass(lv);
        }
        DefaultBiomeFeatures.addDefaultOres(lv);
        DefaultBiomeFeatures.addDefaultDisks(lv);
        if (windswept) {
            DefaultBiomeFeatures.addExtraSavannaTrees(lv);
            DefaultBiomeFeatures.addDefaultFlowers(lv);
            DefaultBiomeFeatures.addWindsweptSavannaGrass(lv);
        } else {
            DefaultBiomeFeatures.addSavannaTrees(lv);
            DefaultBiomeFeatures.addExtraDefaultFlowers(lv);
            DefaultBiomeFeatures.addSavannaGrass(lv);
        }
        DefaultBiomeFeatures.addDefaultMushrooms(lv);
        DefaultBiomeFeatures.addDefaultVegetation(lv);
```

This is BYG (from [GitHub](https://github.com/AOCAWOL/BYG/blob/1.19.X/Common/src/main/java/potionstudios/byg/common/world/biome/BYGOverworldBiomes.java)):
```java
        byg_invokeGlobalOverworldGeneration(generationSettings);

        BiomeDefaultFeatures.addSavannaGrass(generationSettings);
        BiomeDefaultFeatures.addDefaultOres(generationSettings);
        BiomeDefaultFeatures.addDefaultSoftDisks(generationSettings);
        BiomeDefaultFeatures.addDesertVegetation(generationSettings);
        BiomeDefaultFeatures.addSavannaExtraGrass(generationSettings);

        BiomeDefaultFeatures.addDefaultMushrooms(generationSettings);

        BYGDefaultBiomeFeatures.addSparseOakForestTrees(generationSettings);
        BYGDefaultBiomeFeatures.addShrub(generationSettings);
        BYGDefaultBiomeFeatures.addFirecrackerShrubs(generationSettings);
        BYGDefaultBiomeFeatures.addFirecracker(generationSettings);
```

And finally, this is Terrestria (from [GitHub](https://github.com/TerraformersMC/Terrestria/blob/1.19/common/src/main/java/com/terraformersmc/terrestria/biome/OutbackBiomes.java)):
```java
		DefaultBiomeFeatures.addFossils(builder);
		addBasicFeatures(builder);
		DefaultBiomeFeatures.addDefaultOres(builder);
		DefaultBiomeFeatures.addClayOre(builder);
		DefaultBiomeFeatures.addDefaultDisks(builder);
		builder.feature(GenerationStep.Feature.VEGETAL_DECORATION, TerrestriaPlacedFeatures.RARE_YUCCA_PALM_TREES);
		builder.feature(GenerationStep.Feature.VEGETAL_DECORATION, TerrestriaPlacedFeatures.PATCH_DEAD_GRASS);
		builder.feature(GenerationStep.Feature.VEGETAL_DECORATION, TerrestriaPlacedFeatures.ACACIA_DOT_SHRUBS);
		DefaultBiomeFeatures.addSavannaGrass(builder);
		DefaultBiomeFeatures.addDesertDeadBushes(builder);
		DefaultBiomeFeatures.addDefaultMushrooms(builder);
		DefaultBiomeFeatures.addDefaultVegetation(builder);
		DefaultBiomeFeatures.addDesertFeatures(builder);
```

I cannot find the source code for William Wythers' Overhauled Overworld so I can't comment on what their feature order is.  This veers off into the weeds a bit but as a veteran system administrator I would advise against running software with secretive source code (if you must, it should come from a company that could be sued if it is malicious, not from an unidentified individual).

**Comment by gniftygnome** [comment] 2022-09-12 17:57
Analysis of this shows `addDefaultVegetation` and `addDesertVegetation` both include `VegetationPlacedFeatures.PATCH_PUMPKIN` and therefore must occur in the same place relative to other feature placements.  However, as you can see, while Vanilla and Terrestria place the mushrooms first, BYG places the vegetation first.

This is made even more clear by the Vanilla definition of the Desert biome, which includes the following snippet:
```java
        DefaultBiomeFeatures.addDefaultMushrooms(lv2);
        DefaultBiomeFeatures.addDesertVegetation(lv2);
 ```

To put it very bluntly, BYG has got the features in the wrong order and the fact they do not have feature order cycles with Vanilla must be a matter of luck w.r.t. biome placement.  I am not very interested in following their lead on this as it seems certain to cause more problems later.

**Comment by gniftygnome** [comment] 2022-09-12 18:08
BYG issue:  https://github.com/AOCAWOL/BYG/issues/963

**Comment by Gamemassa** [comment] 2022-09-12 20:33
> I was just indicating that the Outback biome can be disabled in the config for anyone having the issue. A simple workaround. And letting you know it seemed to work quite nicely with pretty much all biome mods after disabling the Outback. I am pushing for the inclusion of all the Terraformers mods again though, like we had in aof3.

@dandin87 ~~How does one go about disabling it?~~ Never mind, I figured it out myself right after I asked.
Also, strange that the order of those two lines would cause issues like this (but then I'm fairly new to Minecraft modding as compared to you guys).

**Comment by gniftygnome** [comment] 2022-09-12 22:32
> @dandin87 ~How does one go about disabling it?

For anyone else who needs this, find your config directory and edit the `terrestria/biome.json` file (like `.minecraft/config/terrestria/biome.json` for some loaders f.e.).  Locate "true" next to "outback" and change it to "false".

> Also, strange that the order of those two lines would cause issues like this

Yes, it is annoying to say the least.  It causes a lot of trouble for modders since Mojang did this.  Although I suppose modders could avoid the problem by never reusing any Vanilla features directly.

**Comment by Sunconure11** [comment] 2022-09-17 19:24
https://pastebin.com/9dPbPhRV

I've also noticed this issue happens even without William's.

**Comment by gniftygnome** [comment] 2022-09-17 19:32
> I've also noticed this issue happens even without William's.

Yes, reports indicate either mod is incompatible.  A and B both have issues -> either A or B will cause issues.  It's tough to condense that into a short blurb for the issue title.  I am hoping BYG will fix it on their end.  I'm not sure how to even report it for the William Wythers mod.

**Comment by Sunconure11** [comment] 2022-09-17 19:44
@corgitaco

Can you look at this?

**Comment by gniftygnome** [comment] 2022-09-18 23:29
This is not *fixed* because that requires action on the part of the other mods' authors, but I think I have found a rearrangement of our features which seems to be compatible with Vanilla as well as BYG and Wythers, so I am calling it resolved on our end.  Please report if you can still find any feature order cycles.

**Closed as completed by gniftygnome** 2022-09-18 23:29 UTC

**Comment by Sunconure11** [comment] 2022-09-22 22:26
I ran into this again.

https://mclo.gs/sezUzTV

**Comment by gniftygnome** [comment] 2022-09-22 22:44
> I ran into this again.

The logs only mention Terralith.  Do you have a particular reason to think it was caused by Terrestria?

**Comment by Sunconure11** [comment] 2022-09-22 22:49
I can test. Though I have two other mods that haven't been tested by others against Terrestria; Profundis and Aurora's Decorations.

I've got Galosphere too.

However, I have confirmed they work.

**Comment by Sunconure11** [comment] 2022-09-22 22:53
It's Terrestria. Again.

**Comment by gniftygnome** [comment] 2022-09-22 23:59
> It's Terrestria. Again.

It wasn't Terrestria last time, so I am not certain where the "Again" comes from.

I cannot reproduce the problem using just Terrestria and Terralith.  Can you, using a brand new world, and send me the seed?

Also, please add [Cyanide](https://www.curseforge.com/minecraft/mc-mods/cyanide-fabric/files) to your mods, get it to crash again, and send me the logs.

**Comment by Sunconure11** [comment] 2022-09-23 05:17
@gniftygnome 

https://pastebin.com/EPUGL5pk

**Comment by Sunconure11** [comment] 2022-09-23 08:54
A minor thing of note is that if I don't turn off Moonlight Lib and mods reliant on it, Cyanide refuses to boot.

https://pastebin.com/FwgJc24C

**Comment by Sunconure11** [comment] 2022-09-23 09:09
For the time being, I have Terralith disabled.

**Comment by gniftygnome** [comment] 2022-09-23 17:57
> https://pastebin.com/EPUGL5pk

Unfortunately, it appears an error in one of the Incenduim JSON files is preventing the game from getting to the error we really want (the feature order cycle one).  Generally, Cyanide is supposed to make the game more likely to generate all of the errors before stopping, so I am not certain why that is not happening in this case.  I was hoping we could get an error from Cyanide at least indicating what feature is involved in Terralith (it won't tell us anything about the non-datapack mods).


Having looked at the features in Terralith's Haze Mountain biome and compared them to Terrestria's there is no clear problem with the combination of the two mods (which is supported by my inability to reproduce the error with just those mods).  Also, I do not see any issue with Terralith's Haze Mountain biome feature order in combination with Vanilla biomes.  I am afraid one of the multitude of other mods you have installed is causing the feature order cycle and I can't easily speculate on which mod is actually responsible.
