### ISSUE TITLE
Game Crashing after update

### ISSUE THREAD

**Issue by msadorably** [TerraformersMC/Terrestria#315] opened 2023-08-16 16:43 UTC
Hello! I went to go play mc this morning and it said I needed to update my mods. I did and then things stopped working right and I'm crashing before even loading up mc. ive tried downgrading etc and that does not work. I need both mods create and terrestria as I actively use both of these.

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'create'!

That is my error code and i will provide my crash down below as well as latest log.  

[latest.log](https://github.com/TerraformersMC/Terrestria/files/12361703/latest.log)

[crash-2023-08-16_10.41.00-client.txt](https://github.com/TerraformersMC/Terrestria/files/12361705/crash-2023-08-16_10.41.00-client.txt)

**Comment by gniftygnome** [comment] 2023-08-16 20:13
Duplicate of #314

**Closed as not planned** 2023-08-16 20:14 UTC
Labels: duplicate
