### ISSUE TITLE
Basalt Grass Block

### ISSUE THREAD

**Issue by Popsculpture** [TerraformersMC/Terrestria#49] opened 2019-08-04 12:29 UTC
No texture; I opened up the file and I didn't find the file there either.
![2019-08-04_05 13 41](https://user-images.githubusercontent.com/37611771/62423708-ce00cb00-b678-11e9-9d64-4ed608ecf41c.png)

**Comment by coderbot16** [comment] 2019-08-04 14:41
Can you send the full log as well as the Terrestria jar file?

**Comment by coderbot16** [comment] 2019-08-04 14:41
Not entirely sure how this issue is even possible, but it may be a messed up jar.

**Comment by Popsculpture** [comment] 2019-08-04 15:04
it wont let me post the Jar but here is where i got it: https://www.curseforge.com/minecraft/mc-mods/terrestria/files 

actually i just changed the extension to zip so i can share the exact file. Not sure how to run a log or I would.
[terrestria-1.0.7+build.18.zip](https://github.com/TerraformersMC/Terrestria/files/3465006/terrestria-1.0.7%2Bbuild.18.zip)

**Comment by Popsculpture** [comment] 2019-08-04 15:05
1.14.4 Fabric

**Comment by coderbot16** [comment] 2019-08-04 15:13
Could you also share the full log file on Pastebin or GitHub Gist as well as the mod list? Need to see what may be causing this if the issue is not with the jar.

**Comment by coderbot16** [comment] 2019-08-04 15:23
Are you using a resource pack of any kind?

**Comment by Popsculpture** [comment] 2019-08-04 22:51
I figured it out... The 3D default texture pack was doing it. it's weird that, that was the only texture to be impacted.

**Comment by coderbot16** [comment] 2019-08-04 22:53
The basalt grass block specifically uses the vanilla texture reference for improving texture pack compatibility, so it's surprising that in this case it resulted in breakage. Though, even in that case, it's still odd that the vanilla texture was not present at all...

**Comment by coderbot16** [comment] 2019-08-04 22:58
I'm going to close this because it's not really an issue in Terrestria itself but rather the resource pack unexpectedly changing the resources, but I'm willing to help with patching up the resource pack if needed.

**Closed as completed by coderbot16** 2019-08-04 22:58 UTC

**Comment by Popsculpture** [comment] 2019-08-04 23:55
it's fixed; i' updated resource pack

**Comment by coderbot16** [comment] 2019-08-05 00:10
Great, glad that it's working!
