### ISSUE TITLE
Sakuras... are not pink.

### ISSUE THREAD

**Issue by hanzotitmada** [TerraformersMC/Terrestria#206] opened 2020-11-17 21:33 UTC
So I'll start off by saying I do have fabric seasons installed also, however, it IS currently springtime. The sakura leaves attached to the trunk of the tree are pink, but the rest of the leaves aren't, they're just dark green. However, they have the sakura leaf texture. Some of the trees aren't green, they're a sort of reddish color, and it does seem like being close to the Japanese maple biome increased this reddishness. 

I'd add pictures but minecraft keeps crashing on me, so maybe later.

**Comment by hanzotitmada** [comment] 2020-11-17 21:40
Ok Minecraft working, here's what I mean, this tree I just grew in a little... idk, oak forest biome, this is a reddish one, although I saw several that were more of a dark green. 
![image](https://user-images.githubusercontent.com/74527545/99453820-85afff80-28f3-11eb-8519-b3668f131f21.png)
![image](https://user-images.githubusercontent.com/74527545/99453884-995b6600-28f3-11eb-8654-1421168704ac.png)

**Comment by coderbot16** [comment] 2020-12-08 04:00
This is most likely an issue with OptiFine. There isn't currently a known workaround, and I'm not sure how it could be fixed.

**Comment by coderbot16** [comment] 2020-12-15 21:30
As usual, this is an issue caused by OptiFine being exceedingly dumb. Closing this since this isn't our bug, it needs to be fixed in OptiFine or OptiFabric.

**Closed as completed by coderbot16** 2020-12-15 21:30 UTC
Labels: mod compatibility
