### ISSUE TITLE
[1.18.2-4.0.2] Rubber signs drop oak signs when broken

### ISSUE THREAD

**Issue by Gronglegrowth** [TerraformersMC/Terrestria#276] opened 2022-09-11 05:31 UTC
Seems like their loot tables weren't setup correctly? I've not looked at the other signs but rubber at least is for sure affected by this.

Clarification: Only happens with signs placed on the side of blocks.

**Comment by gniftygnome** [comment] 2022-09-11 07:50
Could you clarify what version of Terrestria this is about?  Versions for Minecraft 1.18.2 should start with 4, not 1.

**Comment by Gronglegrowth** [comment] 2022-09-11 09:05
It's 4.0.2, I must have been reading the version number of a different mod, apologies for that

**Comment by gniftygnome** [comment] 2022-09-12 17:01
I just tested this with 4.0.2 and cannot reproduce.  With bare hand or with axe, either on the wall or on the ground, rubber wood signs break and yield rubber wood signs.  If you would like to provide the full logs I can look for something in there but I'm not certain what is going on otherwise.

**Comment by Gronglegrowth** [comment] 2022-09-13 08:20
[Here's a log](https://mclo.gs/Wi9vwlM) wherein the only actions I took were giving myself a rubber wood sign, placing it, then breaking it, but at a glance it seems like nothing of note's in here. It must be caused by some other mod? The modpack I am using is [here](https://modrinth.com/modpack/midnight-industries/version/1.0.1) if you'd like to experiment with what might be happening.

**Comment by gniftygnome** [comment] 2022-09-13 09:25
This appears to be a difference in behavior of Quilted Fabric API vs. actual Fabric API.  I can reproduce this result when running via [Quilt](https://www.curseforge.com/minecraft/mc-mods/qsl/files/3932586) with only Terrestria installed.  Being as Quilt aims to exactly reproduce Fabric APIs, I suspect this is a bug in Quilted Fabric API (especially since the loot tables in question are generated via Minecraft data generation).  I may try and track it down and/or see if I can work around it if I manage to make time.

**Comment by gniftygnome** [comment] 2023-06-18 04:00
This is finally resolved in the recent releases of our mods for 1.19 - 1.19.2, 1.19.4, and 1.20.x.

**Closed as completed by gniftygnome** 2023-06-18 04:00 UTC
