### ISSUE TITLE
Basalt Strength

### ISSUE THREAD

**Issue by Gitcurt777** [TerraformersMC/Terrestria#67] opened 2019-08-26 14:32 UTC
Any chance basalt will be as strong as stone?
A creeper just let me know that its not... lol.

**Comment by NeusFear** [comment] 2019-08-29 13:38
I believe this was fixed in 1.0.10 when we patched the tools. I just tested on that version to be sure and the issue isn't present.

**Closed as completed** 2019-08-29 13:38 UTC
